import Link from "next/link";
import { redirect } from "next/navigation";
import { isAdmin } from "@/lib/auth";

const sections = [
	["overview", "Start here"], ["daily-work", "Daily work"], ["content", "Content tools"], ["gallery", "Gallery"], ["orders", "Orders & email"], ["troubleshooting", "Troubleshooting"], ["developer", "Developer handoff"],
] as const;

export default async function AdminWikiPage() {
	if (!(await isAdmin())) redirect("/admin");
	return <section className="admin-page wiki-workspace"><div className="container">
		<header className="wiki-hero"><div><p className="eyebrow">Internal knowledge base</p><h1 className="display">Operations Wiki</h1><p className="wiki-lede">A clear, practical guide to running the site—for everyday administrators and the developers who support it.</p></div><div className="wiki-hero-meta"><span className="wiki-status-dot" /> Private admin documentation <Link href="/admin">Back to admin</Link></div></header>
		<div className="wiki-layout"><aside className="wiki-sidebar" aria-label="Wiki sections"><p className="wiki-sidebar-label">On this page</p><nav>{sections.map(([id, label], index) => <a key={id} href={`#${id}`} className={index === 0 ? "current" : ""}><span>{String(index + 1).padStart(2, "0")}</span>{label}</a>)}</nav><div className="wiki-sidebar-note"><strong>Need to make a change?</strong><p>Use the admin tabs, then return here for field-by-field instructions.</p><Link href="/admin">Open admin panel →</Link></div></aside>
			<main className="wiki-content">
				<section id="overview" className="wiki-section wiki-overview"><div className="wiki-section-heading"><span className="wiki-kicker">01 · Orientation</span><h2>Start here</h2><p>The admin panel is the private control room for the website. Changes are made through forms, saved to the site database, and reflected on public pages.</p></div><div className="wiki-quick-grid"><Link href="/admin?view=gallery" className="wiki-quick-card"><span className="wiki-card-number">01</span><strong>Update gallery</strong><small>Upload, describe, hide, or remove photos.</small></Link><Link href="/admin?view=testimonials" className="wiki-quick-card"><span className="wiki-card-number">02</span><strong>Manage testimonials</strong><small>Filter stories by category or year.</small></Link><Link href="/admin/orders" className="wiki-quick-card"><span className="wiki-card-number">03</span><strong>Process an order</strong><small>Review payment, fulfillment, and tracking.</small></Link></div><div className="wiki-callout"><strong>Safe editing routine</strong><span>Sign in → choose a tab → change one thing → save → check the confirmation → view the public page → sign out.</span></div></section>
				<section id="daily-work" className="wiki-section"><div className="wiki-section-heading"><span className="wiki-kicker">02 · Routine</span><h2>Daily work</h2><p>These habits keep content accurate and prevent accidental public changes.</p></div><div className="wiki-flow"><div><b>1</b><strong>Sign in</strong><span>Visit <code>/admin</code> and use private credentials.</span></div><i>→</i><div><b>2</b><strong>Choose a tool</strong><span>Products, Events, Testimonials, Orders, Gallery, or Wiki.</span></div><i>→</i><div><b>3</b><strong>Verify the result</strong><span>Look for confirmation, then check the public page.</span></div></div><div className="wiki-two-column"><div><h3>Sign in and sign out</h3><ol><li>Open the site address followed by <code>/admin</code>.</li><li>Enter the administrator username and password.</li><li>Press Sign out when finished, especially on a shared computer.</li></ol><p>There is one shared administrator account. Never put its password in this Wiki, email, or a screenshot.</p></div><div><h3>What the tabs control</h3><ul><li><strong>Products:</strong> shop catalog and product images.</li><li><strong>Events:</strong> public event pages.</li><li><strong>Testimonials:</strong> approved stories.</li><li><strong>Orders:</strong> paid orders and fulfillment.</li><li><strong>Gallery:</strong> public photo collection.</li><li><strong>Wiki:</strong> this handbook.</li></ul></div></div></section>
				<section id="content" className="wiki-section"><div className="wiki-section-heading"><span className="wiki-kicker">03 · Publishing</span><h2>Content tools</h2><p>Unpublish to hide something temporarily; delete only when it should no longer exist.</p></div><div className="wiki-subsection"><h3>Products</h3><p>Complete name, short name, price, category, description, image, sizes, and optional stock, then save. Enter clothing sizes separated by commas, such as <code>S, M, L, XL, XXL</code>. Use pencil to edit, copy to duplicate, and trash to delete. Featured controls prominent home placement.</p><div className="wiki-note"><strong>Inventory note</strong><span>Stock is informational. Checkout validates product and size but does not automatically deduct inventory.</span></div></div><div className="wiki-subsection"><h3>Events</h3><p>Complete title, dates, type, location, summary, hero title, overview, details, call-to-action, and image. Uncheck Published to hide without losing writing. Use Featured for highlighted placement. For finished events, use Is over and add a verified recap link.</p></div><div className="wiki-subsection"><h3>Testimonials</h3><p>Enter the approved quote exactly. Use Anonymous when identification is not approved. Choose Horseback, Hunting, Fishing, Camping, or General. Use Category and Year filters to locate records.</p></div></section>
				<section id="gallery" className="wiki-section"><div className="wiki-section-heading"><span className="wiki-kicker">04 · Media</span><h2>Gallery operations</h2><p>The Gallery manager controls which approved photographs appear publicly.</p></div><div className="wiki-steps"><div><span>01</span><h3>Review first</h3><p>Exclude gore, graphic injury or medical scenes, duplicates, logos, flyers, posters, advertisements, screenshots, and unapproved images. Check privacy for recognizable people, children, plates, and sensitive locations.</p></div><div><span>02</span><h3>Upload</h3><p>Choose Gallery, select one file or use Ctrl/Command for several, then press Upload images. PNG, JPEG, and WebP are accepted.</p></div><div><span>03</span><h3>Describe</h3><p>Edit every image. Alt text describes what is visible; captions add verified context; tags are comma-separated labels; year must be verified.</p></div><div><span>04</span><h3>Publish or hide</h3><p>Published controls visibility and saves immediately when changed. Unchecking it removes the image from the public gallery without another Save click.</p></div></div><div className="wiki-subsection"><h3>Alt text that helps</h3><p>Write one concise sentence, such as “Two Veterans stand beside a lake after a fishing outing.” Do not write “image of,” guess identities, mention diagnoses, or stuff keywords. Mouseover alt text is not dependable, so the site also uses a hover title and visible lightbox caption.</p></div><div className="wiki-danger"><strong>Delete carefully</strong><span>Trash removes the record and attempts to remove uploaded Blob storage. Keep approved originals in an outside archive.</span></div></section>
				<section id="orders" className="wiki-section"><div className="wiki-section-heading"><span className="wiki-kicker">05 · Commerce</span><h2>Orders & email</h2><p>Payment and fulfillment are separate. Confirm payment before preparing or shipping.</p></div><div className="wiki-order-flow"><div><strong>Customer checks out</strong><span>Name, email, phone, address, notes, product, size, and quantity are collected.</span></div><div><strong>PayPal confirms</strong><span>The server verifies the exact amount and records the paid order.</span></div><div><strong>Team fulfills</strong><span>Admin reviews, prepares, adds tracking, and completes it.</span></div></div><h3>Process a paid order</h3><ol><li>Search by order number, name, email, or PayPal ID.</li><li>Confirm Payment is Paid.</li><li>Review address and every item, size, and quantity.</li><li>Set Processing while preparing.</li><li>Set Shipped with carrier and tracking number.</li><li>Set Completed after delivery.</li></ol><div className="wiki-two-column"><div><h3>Who receives email?</h3><p>Paid-order alerts go to <code>CONTACT_EMAIL_TO</code>. The customer receives confirmation and, when tracking is entered, a shipment email. Contact messages also go there.</p></div><div><h3>How replies work</h3><p>Contact mail replies to the visitor. Customer mail replies to the team address. Pressing Reply should reach the correct person.</p></div></div></section>
				<section id="troubleshooting" className="wiki-section"><div className="wiki-section-heading"><span className="wiki-kicker">06 · Support</span><h2>Troubleshooting</h2><p>Use this table before contacting a developer.</p></div><div className="wiki-troubleshooting"><div><strong>Cannot sign in</strong><span>Verify deployed credentials; rotate them in hosting settings.</span></div><div><strong>Save fails</strong><span>Check <code>DATABASE_URL</code> and database logs.</span></div><div><strong>Upload fails</strong><span>Check <code>BLOB_READ_WRITE_TOKEN</code>, type, and size.</span></div><div><strong>Broken image</strong><span>Verify local asset or Blob URL, then re-upload.</span></div><div><strong>Public page unchanged</strong><span>Confirm save, refresh, and test privately.</span></div><div><strong>Customer paid, no email</strong><span>Search Orders first; payment and email are separate.</span></div></div></section>
				<section id="developer" className="wiki-section wiki-developer"><div className="wiki-section-heading"><span className="wiki-kicker">07 · Handoff</span><h2>Developer handoff</h2><p>Where the important behavior lives for the next developer.</p></div><div className="wiki-tech-grid"><div><span>Web app</span><strong>Next.js 16 · React 19 · TypeScript</strong><p>Pages live in <code>src/app</code>; most are server-rendered.</p></div><div><span>Authentication</span><strong>HTTP-only cookie session</strong><p><code>src/lib/auth.ts</code> uses environment credentials and the <code>vot-admin</code> cookie.</p></div><div><span>Database</span><strong>Neon Postgres</strong><p><code>src/lib/db.ts</code> manages content, gallery, orders, and submissions; empty tables seed from <code>src/lib/data.ts</code>.</p></div><div><span>Media</span><strong>Public assets + Vercel Blob</strong><p>Committed assets are in <code>public/</code>; new upload URLs are saved in Neon.</p></div><div><span>Payments</span><strong>PayPal Checkout</strong><p>Create/capture routes validate exact totals; webhook event keys prevent duplicates.</p></div><div><span>Messaging</span><strong>Nodemailer over SMTP</strong><p><code>src/lib/mail.ts</code> sends contact, order, confirmation, and shipment messages.</p></div></div><h3>Admin mutation path</h3><div className="wiki-code-flow"><code>Admin page</code><span>→</span><code>isAdmin()</code><span>→</span><code>server action</code><span>→</span><code>Neon / Blob</code><span>→</span><code>revalidatePath()</code><span>→</span><code>public page</code></div><h3>Environment and validation</h3><p>Production needs the variables in <code>.env.example</code>. Never commit real values. Run <code>npm run lint</code> and <code>npm run build</code>; test login, saves, gallery upload/delete, filters, sandbox checkout, invoices, emails, mobile, keyboard navigation, and broken images. Google Fonts fetched by <code>next/font</code> may require build network access.</p><p className="wiki-footnote">Known limitations include no automatic size-level inventory deduction, one shared admin account, human gallery moderation, and lazy database schema creation.</p></section>
			</main>
		</div>
	</div></section>;
}
