import { redirect } from "next/navigation";
import { isAdmin } from "@/lib/auth";

export default async function AdminWikiPage() {
	if (!(await isAdmin())) redirect("/admin");
	return <section className="admin-page"><div className="container admin-wiki"><p className="eyebrow">Operations handbook</p><h1 className="display">Admin wiki</h1><p className="prose">A practical guide to maintaining the site.</p>
		<article className="wiki-card"><h2>Gallery</h2><p>Open Gallery in the admin tabs to upload one or multiple approved photos. Edit alt text, captions, tags, year, and publication status, then save metadata. Delete removes a database record and attempts to remove Vercel Blob storage for uploaded images.</p><h3>Content rules</h3><p>Publish authentic outdoor-therapy moments only. Exclude duplicates, gore, logos, flyers, and marketing graphics. Alt text should describe what is visibly important without guessing names, diagnoses, or identities. Captions can add verified context.</p><h2>Testimonials</h2><p>Use the Testimonials tab to edit quotes and assign a category. Public visitors can filter testimonials by category and year. Keep author names and service details accurate and use Anonymous when consent does not allow identification.</p><h2>Products and events</h2><p>Products control the shop catalog, prices, sizes, and stock fields. Events control public event pages and their publication status. Changes require the database and image uploads require BLOB_READ_WRITE_TOKEN.</p><h2>Orders</h2><p>Orders record payment, customer details, line items, invoices, and fulfillment. Use the Orders tab to search, update fulfillment, and add tracking. Shipping notification email is sent once when an order is marked shipped with tracking.</p><h2>Troubleshooting</h2><ul><li>Login failures: verify ADMIN_USERNAME and ADMIN_PASSWORD in the deployment environment.</li><li>Uploads fail: verify BLOB_READ_WRITE_TOKEN and that the file is PNG, JPEG, or WebP.</li><li>Saved content is missing: verify DATABASE_URL and inspect the deployment logs.</li><li>Images show as broken: confirm the URL is local or a valid Blob URL, then run the gallery URL check in QA.</li><li>Email does not send: verify SMTP settings and the contact notification address.</li></ul></article>
	</div></section>;
}
