import Link from "next/link";
import { redirect } from "next/navigation";
import { isAdmin } from "@/lib/auth";

export default async function AdminWikiPage() {
	if (!(await isAdmin())) redirect("/admin");
	return (
		<section className="admin-page">
			<div className="container admin-wiki">
				<p className="eyebrow">Operations handbook</p>
				<h1 className="display">Admin wiki</h1>
				<p className="prose">Plain-language instructions for maintaining the website, plus a technical handoff for the next developer.</p>
				<article className="wiki-card">
					<h2>Start here</h2>
					<p>The admin panel is the private control room for the website. Open <code>/admin</code>, sign in, choose a tab, make a change, and press that section&apos;s Save button. A successful save normally returns you to the list with a green confirmation.</p>
					<ol><li>Open the website address followed by <code>/admin</code>.</li><li>Enter the administrator username and password. Never share these in email or text.</li><li>Choose Products, Events, Testimonials, Orders, Gallery, or Wiki.</li><li>Look for the success message, then refresh the public page in a second tab.</li><li>Press Sign out when finished, especially on a shared computer.</li></ol>
					<p><strong>Remember:</strong> persistent edits require the database. If it is disconnected, seed content may display but saves cannot work.</p>

					<h2>Products</h2><p>Products manages merchandise and sponsorship catalog records. Add by completing name, short name, price, category, description, image, sizes, and optional stock, then press Save product. Enter clothing sizes separated by commas, such as <code>S, M, L, XL, XXL</code>. Use the pencil icon to edit, copy to duplicate, and trash to delete. Featured controls prominent home-page placement. Stock is currently informational and is not automatically reduced during checkout.</p>
					<h2>Events</h2><p>Events manages full public event pages. Complete title, dates, type, location, summary, hero title, overview, details, CTA, and image. Uncheck Published to hide an event without losing its writing. Use Featured for highlighted placement. For completed events, use Is over and add a verified recap link. Check the event listing and detail page after saving.</p>
					<h2>Testimonials</h2><p>Testimonials stores approved quotes, author/service details, photos, categories, years, and publication status. Use Category and Year filters to find records. Use Anonymous when identification is not approved. Uncheck Published to hide a record without deleting it. Alt text should describe what is visible, without guessing identities or medical information.</p>

					<h2>Gallery: step by step</h2>
					<h3>Before uploading</h3><p>Only upload approved mission photographs. Exclude gore, severe injury, graphic medical scenes, duplicates, standalone logos, flyers, posters, advertisements, screenshots, and unapproved images. Check consent and privacy for recognizable people, children, license plates, and sensitive locations.</p>
					<h3>Upload one or many</h3><ol><li>Choose Gallery.</li><li>Press the Images file chooser.</li><li>Select one file, or hold Ctrl (Windows) / Command (Mac) to select several.</li><li>Use PNG, JPEG, or WebP.</li><li>Press Upload images.</li><li>Edit every new image before leaving the page.</li></ol>
					<h3>Edit or remove</h3><ul><li><strong>Alt text:</strong> a short description for someone who cannot see the image. Example: “Two Veterans stand beside a lake after a fishing outing.”</li><li><strong>Caption:</strong> optional visible context, such as the event or activity.</li><li><strong>Tags:</strong> comma-separated labels like <code>fishing, Missouri, community</code>.</li><li><strong>Year:</strong> the verified photo or event year.</li><li><strong>Published:</strong> uncheck to hide without deleting.</li><li><strong>Sort order:</strong> controls relative display order.</li></ul><p>Changing Published saves immediately, so unchecking it removes the image from the public gallery without pressing Save metadata. Use Save metadata for the other fields. Press the trash icon for permanent removal from the gallery; uploaded Blob files are also sent for storage deletion. Keep originals in an outside archive if they may be needed.</p><p>Mouseover alt text is not dependable browser behavior. This site uses alt text, a hover title, and a visible lightbox caption so descriptions work for mouse, keyboard, touch, and screen-reader users.</p>

					<h2>Orders</h2><p>After PayPal completes payment, the server verifies the amount, saves the customer and exact line items, marks the order paid, and sends a team notification to <code>CONTACT_EMAIL_TO</code> plus a confirmation to the customer&apos;s checkout email. Orders contain name, email, phone, shipping address, notes, product, size, quantity, prices, PayPal IDs, and timestamps.</p><ol><li>Search Orders by order number, name, email, or PayPal ID.</li><li>Open the order and confirm Payment is Paid.</li><li>Review the address and every item, size, and quantity.</li><li>Set Processing while preparing.</li><li>Set Shipped with carrier and tracking number.</li><li>Set Completed after delivery.</li></ol><p>Payment and fulfillment are separate. Stock is not yet a size-level inventory system. A shipment email is sent once for a tracking combination.</p>

					<h2>Email: what happens</h2><p>The site sends through the configured SMTP mailbox. Contact form messages and paid-order alerts go to <code>CONTACT_EMAIL_TO</code>. Contact replies use the visitor&apos;s email as Reply-To, so pressing Reply normally answers the visitor. Customer confirmations and shipment notices go to the checkout email and use the team address as Reply-To. If email is missing, check spam, the destination, SMTP settings, and Vercel logs. A paid order remains in Orders even when email is delayed.</p>

					<h2>Troubleshooting</h2><ul><li><strong>Login:</strong> verify deployed ADMIN_USERNAME and ADMIN_PASSWORD; ask a developer to rotate them in hosting settings.</li><li><strong>Save:</strong> verify DATABASE_URL and database connectivity.</li><li><strong>Upload:</strong> verify BLOB_READ_WRITE_TOKEN, accepted type, and file size.</li><li><strong>Broken image:</strong> verify the local asset or Blob URL, then re-upload.</li><li><strong>Public page unchanged:</strong> confirm Save, refresh, and test in a private window.</li></ul>

					<h2>Developer handoff: stack</h2><p><strong>Next.js 16 App Router, React 19, TypeScript:</strong> pages live in <code>src/app</code>; most are Server Components. Admin pages call <code>isAdmin()</code>. Server actions in <code>src/app/admin/actions.ts</code> check authorization again, write data, and call <code>revalidatePath()</code>.</p><p><strong>Authentication:</strong> <code>src/lib/auth.ts</code> compares environment credentials with a timing-safe comparison and sets an HTTP-only <code>vot-admin</code> cookie. It is one shared admin session, not a role system.</p><p><strong>Neon Postgres:</strong> <code>src/lib/db.ts</code> lazily creates/updates tables and maps rows for products, events, testimonials, gallery, orders, order items/events, and submissions. Empty tables seed from <code>src/lib/data.ts</code>.</p><p><strong>Vercel Blob:</strong> uploaded product/event/testimonial/gallery files are stored under prefixes and their public URLs are saved in Neon. <code>@vercel/blob</code> deletion is attempted for uploaded gallery files.</p><p><strong>PayPal:</strong> create-order and capture routes validate catalog data and exact totals; webhook processing is idempotent using order events. <code>src/lib/shop/order-finalization.ts</code> records payment and sends order email.</p><p><strong>Email:</strong> Nodemailer in <code>src/lib/mail.ts</code> uses SMTP for contact, paid-order, customer-confirmation, and shipment messages.</p><p><strong>Hosting:</strong> Vercel runs the app; `.env.example` documents Neon, Blob, PayPal, SMTP, and admin variables. Never commit real values.</p><p><strong>Validation:</strong> run <code>npm run lint</code> and <code>npm run build</code>. Test login, all content saves, gallery batch upload/delete, filters, sandbox checkout, invoice, email, mobile layout, keyboard navigation, and broken images. Google Fonts fetched by <code>next/font</code> may require build network access.</p>
					<p><Link className="text-link" href="/admin">Return to the admin panel</Link></p>
				</article>
			</div>
		</section>
	);
}
