import { neon } from "@neondatabase/serverless";
import fs from "node:fs";
const url = fs.readFileSync(".env.local","utf8").split(/\r?\n/).find(l=>l.startsWith("DATABASE_URL=")).slice(13).replace(/^["']|["']$/g,"");
const sql = neon(url);
const [s] = await sql`SELECT image, photo_galleries, gallery_tag FROM field_stories WHERE slug='flint-hills-kansas-turkey-hunt-2026'`;
const g = Array.isArray(s.photo_galleries)? s.photo_galleries : JSON.parse(s.photo_galleries||"[]");
console.log("story hero:", s.image, "| gallery_tag:", s.gallery_tag);
console.log("story galleries:", g.map(x=>`${x.title} (${x.photos.length})`).join(", ") || "(none)");
const rows = await sql`SELECT src FROM gallery_images WHERE src LIKE '%flint-hills%' ORDER BY src`;
console.log("gallery_images with flint-hills:", rows.length);
for (const r of rows) console.log("  ", r.src);
